language: python
env:
    DATA_NAMESPACE="http://vivo.school.edu/individual/"
    VIVO_URL="http://localhost/vivo"
    VIVO_EMAIL="xxx"
    VIVO_PASSWORD="xxx"
python:
  - "2.7"
install:
  - pip install -U pip wheel
  - pip install setuptools==24.0.3
  - pip install -r requirements.txt
script: python -m unittest discover
notifications:
  email:
    - lawlesst@gmail.com
